services:
  app:
    build:
      context: .
    ports:
      - "5001:5001"
    restart: on-failure

  proxy:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static/:/app-static/
    depends_on:
      - app
