name: CI with OpenID Connect

on:
    push:
        branches: [ feat-deploy-azure ]
        paths:
          - "static/"
          - "assets/"
          - "index.data"
          - "index.wasm"
          - "index.js"
          - "index.html"
    workflow_dispatch:

permissions:
      id-token: write
      contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            for f in index.html index.wasm index.js index.data; do
              az storage blob upload-batch --account-name "${{ secrets.STORAGE_ACCOUNT }}" --auth-mode key -d '$web' -s . --pattern "$f" --overwrite true
            done

            az storage blob upload-batch --account-name "${{ secrets.STORAGE_ACCOUNT }}" --auth-mode key -d '$web/static' -s ./static --overwrite true
            az storage blob upload-batch --account-name "${{ secrets.STORAGE_ACCOUNT }}" --auth-mode key -d '$web/assets' -s ./assets --overwrite true

    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az afd endpoint purge --resource-group ${{ secrets.CDN_RESOURCE_GROUP }} --profile-name ${{ secrets.CDN_PROFILE }} --endpoint-name personalportfolio-dvgfemd6brd2d7f6.z01.azurefd.net --domains anrayliu.ca, www.anrayliu.ca --content-paths '/*'

  # Azure logout
    - name: logout
      run: |
            az logout
      if: always()